In [3]:
import numpy

In [5]:
numpy

<module 'numpy' from 'C:\\Users\\HP\\Documents\\an\\lib\\site-packages\\numpy\\__init__.py'>

In [6]:
import numpy as np 

In [7]:
arr = np.array([9,2,4,1,6,8,10, 7])

In [8]:
arr

array([ 9,  2,  4,  1,  6,  8, 10,  7])

In [9]:
#sort an array sort method
np.sort(arr)
#this creates a sorted copy of the array. it doesn't change
#the original array

array([ 1,  2,  4,  6,  7,  8,  9, 10])

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [11]:
#concatenate both arrays using np.concatenate
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
type(a)

In [ ]:
#0-D array np.array(5)
arr0 = np.array(5)
arr0

In [ ]:
#1-D array np.array([1,2,3,4])
arr1 = np.array([1,2,3,4])
arr1

In [ ]:
# 2-D array np.array([[1,2,3,4], [5,6,7,8]])
arr2 =  np.array([[1,2,3,4], [5,6,7,8]])
arr2

In [ ]:
# 3-D array # 3rd order tensor 
arr3 = np.array([[[1,2,3,4], [4,5,6,7], [8,9,10,11]]])
arr3

In [ ]:
#creating arrays with numpy 
#create an array within a specified range 

np.arange(0,10)

In [ ]:
np.arange(1,11)

In [ ]:
#specify your step size with a 3rd arg,

np.arange(1,11,2)

In [ ]:
print(dir(np))

In [ ]:
#other arrays you can create
#arrays of zeros

np.zeros(5)


In [ ]:
#array of ones 
np.ones(4)

In [ ]:
#2-D arrays of zeros and ones 

np.zeros((3,3))

In [ ]:
np.ones((3,4))

In [ ]:
#Creating custom Arrays 
#use linspace 

#np.linspace(lower_bound, upper_bound, no_of_values)

np.linspace(1,11,100)

In [ ]:
arr3 = np.linspace(1,11,100)
arr3.shape

In [ ]:
arr4 = np.array([[1,2,3], [2,4,6]])
arr4.shape

In [ ]:
arr3.dtype

In [ ]:
arr4.dtype

In [ ]:
#Min and Max values in an array by using min() & max()
print(arr3.min())
print('-'* 40)
print(arr3.max())

In [ ]:
#find the position using the argmax or argmin methods 
print(arr3.argmin())
print('-'* 30)
print(arr3.argmax())

In [ ]:
arr = np.array([9,2,4,1,6,8,10, 7])
print(arr.argmax())
print(arr.argmin())

In [ ]:
#Generating random values 
# random values btw 0 and 1 use : np.random.rand()

rd1 = np.random.rand(3)
rd1

In [ ]:
rd2 = np.random.randint(10)
rd2


In [ ]:
from numpy import random as rnd

In [ ]:
x = rnd.randint(100, size=(5))
x

In [ ]:
y = rnd.rand(5,3)
y

In [ ]:
#Generate random nos from an array of values using 
#choice

x = rnd.choice([2,4,6,7])
print(x)

In [ ]:
#2-D array from a random.choice 

y = rnd.choice([2,4,6,7], size=(2,2))
y

In [ ]:
#Random Distribution 
#this is a set of random numbers that follow a certain probability 
#density function

# A probability density function describes a continous probability
#e.g probability of all values in array y



In [ ]:
z = rnd.choice([2,4,6,7], p=[0.1,0.3,0.5,0.1], size=(2,2))
print(z)

In [ ]:
#Manipulating Arrays 

arr4 = np.arange(5, 101,5)
arr4

In [ ]:
#arr4 is vector with 20values

#We can change it to a matrix by using the reshape method

arr4b = arr4.reshape(5,4)
arr4b

In [ ]:
arr4b[1:3,2:4]
#1:3 signifies the rows 
#sliced form row 1 to row 3, 3 excluded
#Note that rows start zero, 0

#2:4 signifies the columns 
# sliced from col 2 to 4, 4 excluded 
#Columns also start from index 0 


In [ ]:
#more slicing 
arr4b[3,:] #returns the entire 4th row 

In [ ]:
arr5 = arr4b
arr5 #this is not a true copy 
arr5b = arr4b.copy() # this is a true copy

In [ ]:
arr5

In [ ]:
arr5[2,:] = 100

In [ ]:
arr5

In [ ]:
arr4b

In [ ]:
arr5b

In [ ]:
arr5b > 50

In [ ]:
arr5b <= 40 #comparison operators 

In [ ]:
#arithmetic operations on arrays 
#+ - / * % 

arr1 = np.arange(0,11)
arr2 = np.arange(0,21,2)

In [ ]:
arr1

In [ ]:
arr2

In [ ]:
print(arr1.size, arr2.size)

In [ ]:
#Arithmetic ops
print(arr1 + arr2)

In [ ]:
print(arr1 - arr2)

In [ ]:
print(arr1 / arr2)